### ISSUE TITLE
PIL decompression bomb error when opening sample image

### ISSUE THREAD

**Issue by tathey1** [brain-image-library/napari-bil-data-viewer#1]
Hi! I had no trouble installing the plugin, however when I load the first sample (mouseID_362188-191815), I get the following error:

```
Traceback (most recent call last):
  File "/Users/thomasathey/Documents/mimlab/mouselight/docs_env/lib/python3.8/site-packages/magicgui/widgets/_bases/value_widget.py", line 59, in _on_value_change
    self.changed.emit(value)
  File "psygnal/_signal.py", line 612, in psygnal._signal.SignalInstance.emit
  File "/Users/thomasathey/Documents/mimlab/mouselight/docs_env/lib/python3.8/site-packages/magicgui/events.py", line 83, in _run_emit_loop
    cb(*args[:max_args])
  File "/Users/thomasathey/Documents/mimlab/mouselight/docs_env/lib/python3.8/site-packages/magicgui/widgets/_function_gui.py", line 188, in _disable_button_and_call
    self.__call__()
  File "/Users/thomasathey/Documents/mimlab/mouselight/docs_env/lib/python3.8/site-packages/magicgui/widgets/_function_gui.py", line 285, in __call__
    value = self._function(*bound.args, **bound.kwargs)
  File "/Users/thomasathey/Documents/mimlab/mouselight/docs_env/lib/python3.8/site-packages/napari_bil_data_viewer/bil_data_loader_widget.py", line 71, in load_bil_data
    sampleImage = getImage(ii[0])
  File "/Users/thomasathey/Documents/mimlab/mouselight/docs_env/lib/python3.8/site-packages/napari_bil_data_viewer/bil_data_loader_widget.py", line 59, in getImage
    return io.imread(f)
  File "/Users/thomasathey/Documents/mimlab/mouselight/docs_env/lib/python3.8/site-packages/skimage/io/_io.py", line 48, in imread
    img = call_plugin('imread', fname, plugin=plugin, **plugin_args)
  File "/Users/thomasathey/Documents/mimlab/mouselight/docs_env/lib/python3.8/site-packages/skimage/io/manage_plugins.py", line 207, in call_plugin
    return func(*args, **kwargs)
  File "/Users/thomasathey/Documents/mimlab/mouselight/docs_env/lib/python3.8/site-packages/skimage/io/_plugins/imageio_plugin.py", line 10, in imread
    return np.asarray(imageio_imread(*args, **kwargs))
  File "/Users/thomasathey/Documents/mimlab/mouselight/docs_env/lib/python3.8/site-packages/imageio/core/functions.py", line 265, in imread
    reader = read(uri, format, "i", **kwargs)
  File "/Users/thomasathey/Documents/mimlab/mouselight/docs_env/lib/python3.8/site-packages/imageio/core/functions.py", line 186, in get_reader
    return format.get_reader(request)
  File "/Users/thomasathey/Documents/mimlab/mouselight/docs_env/lib/python3.8/site-packages/imageio/core/format.py", line 170, in get_reader
    return self.Reader(self, request)
  File "/Users/thomasathey/Documents/mimlab/mouselight/docs_env/lib/python3.8/site-packages/imageio/core/format.py", line 221, in __init__
    self._open(**self.request.kwargs.copy())
  File "/Users/thomasathey/Documents/mimlab/mouselight/docs_env/lib/python3.8/site-packages/imageio/plugins/pillow.py", line 127, in _open
    Image._decompression_bomb_check(self._im.size)
  File "/Users/thomasathey/Documents/mimlab/mouselight/docs_env/lib/python3.8/site-packages/PIL/Image.py", line 2905, in _decompression_bomb_check
    raise DecompressionBombError(
PIL.Image.DecompressionBombError: Image size (556323868 pixels) exceeds limit of 178956970 pixels, could be decompression bomb DOS attack.
```

Here are some details of my setup:
- Macbook Pro - 2.6GHz 6-Core intel Core i7 w/ 32 GB
- macOS 10.15.7
- python 3.8
- napari 0.4.12
- napari-bil-data-viewer 0.1.2

Any easy way to work around this? Happy to provide more info. I may pursue increasing `PIL.Image.MAX_IMAGE_PIXELS`

**Comment by AlanMWatson** [comment]
Thanks @tathey1!.

A couple of thoughts:

1)  It looks like skimage.io is calling PIL.  I am curious if adjusting the size of PIL.Image.MAX_IMAGE_PIXELS will solve your problem.  Please let me know if you try this and how it works.  Meanwhile, I will look into an alternative means to open images that bypasses PIL or removes the size limits.

2) This has not come up on any other systems that we have tested.  From the tracebacks (although its not clear to me) it looks like you may have installed the plugin using the menu in a previous install of napari.  If so, I wonder if it may be specific to the environment that you are using.  If that is correct, can you please try installing napari/plugin in a fresh environment and reporting how that works.  Instructions here: https://www.napari-hub.org/plugins/napari-bil-data-viewer.  

Thanks again for your help!
Alan

**Comment by tathey1** [comment]
I tried both, and they both worked! I personally executed `PIL.Image.MAX_IMAGE_PIXELS = 1056323868` right before launching napari. Also, I know this is due to the data, not the software, but I wanted to say it took me a couple minutes to realize the default contrast limits were way off. I thought it was some sort of bug at first. Once I lowered the upper limit, things looked good.

**Comment by AlanMWatson** [comment]
Thanks @tathey1!  

1.  It is good to know that a fresh environment worked for you.  

2.  Thanks for the tip on raising the PIL max pixel limit.  For now, I am going close this issue since it seems to have been specific to your environment.  However, I will continue to look into modifying how images are opened that does not depend on PIL.  We expect that future datasets will continue to increase in size and what to avoid this as a limitation

3.  Contrast Limits:  You are correct, the contrast limits are 'way off' for these datasets such that the first image to load appears to be blank until the upper limit is adjusted.  Because the amount of data in each z-slice can vary dramatically, it is difficult to predict what the proper contrast limits should be when opening a dataset.  Currently, the limits are set manually according to the data type (16 bit = 0:65535).  I realize that this is not ideal, and we will look to improve it going forward.

Thanks again!
Alan
